sudo: required
services:
 - docker

before_install:
 - docker build -t chlaache/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true chlaache/docker-react npm run test

deploy:
 provider: elasticbeanstalk
 region: "eu-west-1"
 app: "docker_react"
 env: "Dockerreact-env-1"
 bucket_name: "elasticbeanstalk-eu-west-1-727849506101"
 bucket_path: "docker_react"
 on:
  branch: master
 access_key_id: "$ACCESS_KEY"
 secret_access_key: "$SECRET_ACCESS_KEY"