on: push
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::727849506101:user/docker_react_system
          aws-region: eu-west-1
      - name: Get secret
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids:
            docker_react_secret
          parse-json-secrets: true
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build docker images
        run: docker build -t chlaache/docker-react -f Dockerfile.dev .
      - name: Run tests
        run: docker run -e CI=true chlaache/docker-react npm run test