name: Test Frontend
on:
  pull_request:
    branches: master
    types: [opened, reopened]
    
permissions:
  id-token: write
  contents: write

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build docker images
        run: docker build -t chlaache/docker-react -f Dockerfile.dev .
      - name: Run tests
        run: docker run -e CI=true chlaache/docker-react npm run test    
